### ISSUE TITLE
这个打开没有任务调度模块

### ISSUE THREAD

**Issue by LyMysterious** [iamoldli/NetModular.Module.Quartz#1]
我手动在地址栏输入/quartz/group 这个页面提示我无权访问,是屏蔽掉了吗
![image](https://user-images.githubusercontent.com/34183453/76597077-9e813d80-653a-11ea-89f6-947d8e12cd2b.png)
![image](https://user-images.githubusercontent.com/34183453/76597114-ab9e2c80-653a-11ea-8e4b-6b40ad909297.png)

**Comment by iamoldli** [comment]
自动创建数据库并初始化数据，只有Admin模块的数据，Quartz本身的并没有，你需要自行添加菜单，并给角色绑定菜单才行
